const translations = {
    en: {
      "facility-name-1": "Ugnayang La Salle",
      "facility-description-1": "Ugnayang La Salle, the largest event venue at De La Salle University-Dasmariñas, features full air-conditioning and ample seating for concerts, conferences, and ceremonies.",
      "facility-capacity-value-1": "Up to 2000 people",
      "tag-event-venue": "Event Venue",
      "tag-large-capacity": "Large Capacity",
      "event-details-title": "Event Details",


      "facility-name-2": "Football Field",
      "facility-description-2": "The DLSU-D Football Field serves as a premier venue for football practice, mass demonstrations, and various civic and cultural events. Its expansive and well-maintained grounds provide the perfect setting for athletic training and large-scale gatherings.",
      "facility-capacity-value-2": "Up to 400 people",
      "field-tag1": "Sports",
      "field-tag2": "Concerts",
      "field-tag3": "Student Activities",
      "field-tag4":"Cultural Events",

      "facility-name-2": "Football Field",
      "facility-description-2": "The DLSU-D Football Field serves as a premier venue for football practice, mass demonstrations, and various civic and cultural events. Its expansive and well-maintained grounds provide the perfect setting for athletic training and large-scale gatherings.",
      "facility-capacity-value-2": "Up to 400 people",
      "field-tag1": "Sports",
      "field-tag2": "Concerts",
      "field-tag3": "Student Activities",
      "field-tag4":"Cultural Events",

      "facility-name-3": "Grandstand",
      "facility-description-3": "The DLSU-D Grandstand provides a place for audiences to watch sporting events as they happen. It also occasionally used as a venue for alternative classes when faculty and students opt to go outdoors for a different learning atmosphere.",
      "facility-capacity-value-3": "Up to 400 people",
      "grand-tag1": "Events",
      "grand-tag2": "Concerts",
      "grand-tag3": "Student Activities",

      "facility-name-4": "Mth Court",
      "facility-description-4": "The MTH Court is a versatile venue designed for sports and events, offering a spacious and dynamic space perfect for athletic activities, tournaments, and special gatherings.",
      "facility-capacity-value-4": "Up to 500 people",
      "mth-tag1": "Sports",
      "mth-tag2": "Events",


      "facility-name-5": "RCC Assembly Hall",
      "facility-description-5": "The RCC Assembly Hall is a flexible venue that can host up to 60 guests in a classroom setup, 50 in a conference setup with tables, and 40 for recollection activities. It features air conditioning, a glassboard, and a wide screen, ensuring a comfortable and functional space for various gatherings.",
      "facility-capacity-value-5": "Up to 60 people",
      "ass-tag1": "Spiritual Activities",
      "ass-tag2": "Conferences",

      "facility-name-6": "RCC Chapel Hall",
      "facility-description-6": "The RCC Chapel offers a serene and sacred space for meetings, conferences, spiritual activities, and moments of reflection. Designed to inspire faith and foster a sense of community, this venue is perfect for gatherings that seek to nurture the spirit and strengthen connections.",
      "facility-capacity-value-6": "Up to 100 people",
      "chap-tag1": "Spiritual Activities",
      "chap-tag2": "Conferences",


      "facility-name-7": "RCC Corporate Hall",
      "facility-description-7": "The RCC Corporate Hall is a versatile and comfortable venue, accommodating up to 60 guests in a classroom setup, 50 in a conference setup with tables, and 40 for recollections. Fully equipped with air conditioning, a glassboard, and a wide screen, it’s an ideal space for professional and spiritual gatherings alike.",
      "facility-capacity-value-7": "Up to 60 people",
      "corp-tag1": "Classroom",
      "corp-tag2": "Conferences",

      "facility-name-8": "Swimming Pool",
      "facility-description-8": "The University invested in an Olympic-sized Pool to serve as the venue for students' Physical Education classes and certificate programs for swimming. A fine resort impression, surrounded with the usual, nature orientation, the pool has concrete, covered bleachers on the left and on the other, 12 wide shower areas and 52 dressing cubicles.",
      "facility-capacity-value-8": "Up to 25 people",
      "swim-tag1": "Sports",
      "swim-tag2": "Olympic-sized",
      "swim-tag3": "Physical Education",

      "facility-name-9": "Track oval",
      "facility-description-9": "Situated near Ugnayang La Salle, the track oval is available for use by the University’s students and personnel for exercise and training. The football field also provides a location for student athletes to train during the weekdays.",
      "facility-capacity-value-9": "Up to 500 people",
      "oval-tag1": "Sports",
      "oval-tag2": "Training",
      "oval-tag3": "Physical Education",




      "facility-capacity-1": "Capacity:",
      "event-name-label": "Event Name",
      "attendees-label": "Number of Attendees",
      "pick-date-time": "Pick a Date and Time",
      "morning": "Morning",
      "afternoon": "Afternoon",
      "regular-hours": "Regular Hours",
      "late-hours": "Late Hours",
      "evening": "Evening",
      "wholeday": "Wholeday",
      "schedule-btn": "Schedule Event",
    },
    es: {
      "facility-name-1": "Ugnayang La Salle",
      "facility-description-1": "Ugnayang La Salle es el lugar de eventos más grande de la Universidad De La Salle-Dasmariñas, con aire acondicionado y amplias instalaciones para conferencias y ceremonias.",
      "facility-capacity-1": "Capacidad:",
      "facility-capacity-value-1": "Hasta 2000 personas",
      "tag-event-venue": "Lugar de eventos",
      "tag-large-capacity": "Gran capacidad",
      "event-details-title": "Detalles del evento",

      "facility-name-2": "Campo de Fútbol",
      "facility-description-2": "El Campo de Fútbol de DLSU-D es un lugar de primer nivel para la práctica del fútbol, demostraciones masivas y diversos eventos cívicos y culturales. Sus amplios y bien mantenidos terrenos brindan el entorno perfecto para el entrenamiento atlético y reuniones de gran escala.",
      "facility-capacity-value-2": "Hasta 400 personas",
      "field-tag1": "Deportes",
      "field-tag2": "Conciertos",
      "field-tag3": "Actividades Estudiantiles",
      "field-tag4":" Eventos Culturales",

      "facility-name-3": "Grada",
      "facility-description-3": "La Grada de DLSU-D ofrece un lugar para que el público vea los eventos deportivos mientras ocurren. También se usa ocasionalmente como un lugar para clases alternativas cuando los profesores y estudiantes optan por ir al aire libre para un ambiente de aprendizaje diferente.",
      "facility-capacity-value-3": "Hasta 400 personas",
      "grand-tag1": "Eventos",
      "grand-tag2": "Conciertos",
      "grand-tag3": "Actividades Estudiantiles",

      "facility-name-4": "Mth Court",
      "facility-description-4": "El MTH Court es un lugar versátil diseñado para deportes y eventos, ofreciendo un espacio amplio y dinámico perfecto para actividades atléticas, torneos y reuniones especiales.",
      "facility-capacity-value-4": "Hasta 500 personas",
      "mth-tag1": "Deportes",
      "mth-tag2": "Eventos",


      "facility-name-5": "Salón de Asamblea RCC",
      "facility-description-5": " El Salón de Asamblea RCC es un lugar flexible que puede albergar hasta 60 personas en una configuración de aula, 50 en una configuración de conferencia con mesas y 40 para actividades de recollection. Cuenta con aire acondicionado, pizarra de vidrio y una pantalla grande, asegurando un espacio cómodo y funcional para diversas reuniones.",
      "facility-capacity-value-5": "Hasta 60 personas",
      "ass-tag1": "Actividades Espirituales",
      "ass-tag2": "Conferencias",

      "facility-name-6": "Capilla RCC",
      "facility-description-6": "La Capilla RCC ofrece un espacio sereno y sagrado para reuniones, conferencias, actividades espirituales y momentos de reflexión. Diseñado para inspirar la fe y fomentar el sentido de comunidad, este lugar es perfecto para reuniones que buscan nutrir el espíritu y fortalecer las conexiones.",
      "facility-capacity-value-6": "Hasta 100 personas",
      "chap-tag1": "Actividades Espirituales",
      "chap-tag2": "Conferencias",


      "facility-name-7": "Salón Corporativo RCC",
      "facility-description-7": "El Salón Corporativo RCC es un lugar versátil y cómodo, con capacidad para hasta 60 personas en una configuración de aula, 50 en una configuración de conferencia con mesas, y 40 para recollections. Equipado con aire acondicionado, pizarra de vidrio y una pantalla grande, es un lugar ideal tanto para reuniones profesionales como espirituales.",
      "facility-capacity-value-7": "Hasta 60 personas",
      "corp-tag1": "Aula",
      "corp-tag2": "Conferencias",

      "facility-name-8": "Piscina",
      "facility-description-8": "La Universidad invirtió en una piscina olímpica para servir como lugar para las clases de Educación Física de los estudiantes y programas de certificación en natación. Con una buena impresión de resort, rodeada de naturaleza, la piscina tiene graderías cubiertas de concreto a la izquierda, y en el otro lado hay 12 duchas amplias y 52 cubículos de vestuario.",
      "facility-capacity-value-8": "Hasta 25 personas",
      "swim-tag1": "Deportes",
      "swim-tag2": "Olímpica",
      "swim-tag3": " Educación Física",

      "facility-name-9": "Óvalo de Atletismo",
      "facility-description-9": "Situado cerca de Ugnayang La Salle, el óvalo de atletismo está disponible para su uso por los estudiantes y personal de la Universidad para ejercicio y entrenamiento. El campo de fútbol también proporciona un lugar para que los atletas estudiantes entrenen durante la semana.",
      "facility-capacity-value-9": "Up to 500 people",
      "oval-tag1": "Sports",
      "oval-tag2": "Training",
      "oval-tag3": "Physical Education",


      "event-name-label": "Nombre del evento",
      "attendees-label": "Número de asistentes",
      "pick-date-time": "Seleccione una fecha y hora",
      "morning": "Mañana",
      "afternoon": "Tarde",
      "regular-hours": "Horas regulares",
      "late-hours": "Horas tardías",
      "evening": "Noche",
      "wholeday": "Todo el día",
      "schedule-btn": "Programar evento",
    },
    fr: {
      "facility-name-1": "Ugnayang La Salle",
      "facility-description-1": "Ugnayang La Salle, le plus grand lieu d'événements de l'Université De La Salle-Dasmariñas, dispose de la climatisation et d'une grande capacité pour des concerts, conférences et cérémonies.",
      "facility-capacity-1": "Capacité :",
      "facility-capacity-value-1": "Jusqu'à 2000 personnes",
      "tag-event-venue": "Lieu d'événement",
      "tag-large-capacity": "Grande capacité",
      "event-details-title": "Détails de l'événement",

      "facility-name-2": "Terrain de Football",
    "facility-description-2": "Le terrain de football de DLSU-D sert de lieu principal pour les entraînements de football, les démonstrations massives et divers événements civiques et culturels. Ses vastes terrains bien entretenus offrent un cadre parfait pour l'entraînement athlétique et les rassemblements de grande envergure.",
    "facility-capacity-value-2": "Jusqu'à 400 personnes",
    "field-tag1": "Sports",
    "field-tag2": "Concerts",
    "field-tag3": "Activités Étudiantes",
    "field-tag4": "Événements Culturels",

    "facility-name-3": "Tribune",
    "facility-description-3": "La tribune de DLSU-D offre un espace pour que le public regarde les événements sportifs en direct. Elle est également utilisée occasionnellement comme un lieu pour des cours alternatifs lorsque les professeurs et les étudiants choisissent de sortir pour un environnement d'apprentissage différent.",
    "facility-capacity-value-3": "Jusqu'à 400 personnes",
    "grand-tag1": "Événements",
    "grand-tag2": "Concerts",
    "grand-tag3": "Activités Étudiantes",

    "facility-name-4": "Mth Court",
    "facility-description-4": "Le MTH Court est un lieu polyvalent conçu pour les sports et les événements, offrant un espace spacieux et dynamique, parfait pour les activités athlétiques, les tournois et les rassemblements spéciaux.",
    "facility-capacity-value-4": "Jusqu'à 500 personnes",
    "mth-tag1": "Sports",
    "mth-tag2": "Événements",

    "facility-name-5": "Salle des Assemblées RCC",
    "facility-description-5": "La salle des assemblées RCC est un espace flexible pouvant accueillir jusqu'à 60 personnes en configuration de salle de classe, 50 en configuration de conférence avec des tables, et 40 pour des activités de recollection. Elle est équipée de la climatisation, d'un tableau en verre et d'un grand écran, assurant un espace confortable et fonctionnel pour divers rassemblements.",
    "facility-capacity-value-5": "Jusqu'à 60 personnes",
    "ass-tag1": "Activités Spirituelles",
    "ass-tag2": "Conférences",

    "facility-name-6": "Salle de Chapelle RCC",
    "facility-description-6": "La chapelle RCC offre un espace serein et sacré pour des réunions, des conférences, des activités spirituelles et des moments de réflexion. Conçue pour inspirer la foi et favoriser un sentiment de communauté, ce lieu est parfait pour des rassemblements qui cherchent à nourrir l'esprit et renforcer les liens.",
    "facility-capacity-value-6": "Jusqu'à 100 personnes",
    "chap-tag1": "Activités Spirituelles",
    "chap-tag2": "Conférences",

    "facility-name-7": "Salle Corporative RCC",
    "facility-description-7": "La salle corporative RCC est un lieu polyvalent et confortable pouvant accueillir jusqu'à 60 invités en configuration de salle de classe, 50 en configuration de conférence avec des tables, et 40 pour des recollections. Entièrement équipée de la climatisation, d'un tableau en verre et d'un grand écran, c'est un espace idéal pour des rassemblements professionnels et spirituels.",
    "facility-capacity-value-7": "Jusqu'à 60 personnes",
    "corp-tag1": "Salle de classe",
    "corp-tag2": "Conférences",

    "facility-name-8": "Piscine",
    "facility-description-8": "L'université a investi dans une piscine de taille olympique pour servir de lieu pour les cours d'éducation physique des étudiants et les programmes de certification en natation. L'impression d'un complexe hôtelier, entourée de nature, la piscine dispose de gradins en béton couvert à gauche et, de l'autre côté, de 12 douches spacieuses et 52 cabines de vestiaire.",
    "facility-capacity-value-8": "Jusqu'à 25 personnes",
    "swim-tag1": "Sports",
    "swim-tag2": "Taille Olympique",
    "swim-tag3": "Éducation Physique",

    "facility-name-9": "Piste d'Athlétisme",
    "facility-description-9": "Située près de Ugnayang La Salle, la piste d'athlétisme est disponible pour l'utilisation des étudiants et du personnel de l'université pour l'exercice et l'entraînement. Le terrain de football sert également de lieu pour que les athlètes s'entraînent durant la semaine.",
    "facility-capacity-value-9": "Jusqu'à 500 personnes",
    "oval-tag1": "Sports",
    "oval-tag2": "Entraînement",
    "oval-tag3": "Éducation Physique",


      "event-name-label": "Nom de l'événement",
      "attendees-label": "Nombre de participants",
      "pick-date-time": "Choisissez une date et une heure",
      "morning": "Matin",
      "afternoon": "Après-midi",
      "regular-hours": "Heures régulières",
      "late-hours": "Heures tardives",
      "evening": "Soirée",
      "wholeday": "Toute la journée",
      "schedule-btn": "Planifier l'événement",
    },
    bi: {
      "facility-name-1": "Ugnayang La Salle",
      "facility-description-1": "Ang Ugnayang La Salle ang pinakadako nga lugar sa De La Salle University-Dasmariñas alang sa mga okasyon, adunay aircon ug daghang lingkuranan para sa mga concerts, conferences, ug ceremonies.",
      "facility-capacity-1": "Kapasidad:",
      "facility-capacity-value-1": "Hangtud sa 2000 ka tawo",
      "tag-event-venue": "Lugar sa Kalihokan",
      "tag-large-capacity": "Dako nga Kapasidad",
      "event-details-title": "Mga Detalye sa Kalihokan",

      "facility-name-2": "Football Field",
    "facility-description-2": "Ang football field sa DLSU-D mao ang nag-unang lugar para sa mga practice sa football, mga dako nga demonstrasyon, ug lain-laing mga kultural ug civic nga kalihokan. Ang dagkong ug maayong pag-atiman nga yuta nagtanyag og hingpit nga lugar para sa athletic training ug dako nga mga katigom.",
    "facility-capacity-value-2": "Hangtod sa 400 ka tawo",
    "field-tag1": "Sports",
    "field-tag2": "Mga Konsyerto",
    "field-tag3": "Mga Aktibidad sa Estudyante",
    "field-tag4": "Mga Kultural nga Event",

    "facility-name-3": "Grandstand",
    "facility-description-3": "Ang grandstand sa DLSU-D naghatag og lugar alang sa publiko nga motan-aw sa live sporting events. Gigamit usab kini kasagaran ingon usa ka lugar alang sa alternative nga mga klase kon ang mga magtutudlo ug estudyante magpili nga mag-outdoor alang sa lain-laing setting sa pagkat-on.",
    "facility-capacity-value-3": "Hangtod sa 400 ka tawo",
    "grand-tag1": "Mga Event",
    "grand-tag2": "Mga Konsyerto",
    "grand-tag3": "Mga Aktibidad sa Estudyante",

    "facility-name-4": "Mth Court",
    "facility-description-4": "Ang MTH Court usa ka versatile nga lugar nga gidesinyo para sa sports ug mga event, nagtanyag og halapad ug dinamikong espasyo nga perpekto para sa athletic activities, mga torneo, ug espesyal nga mga katigom.",
    "facility-capacity-value-4": "Hangtod sa 500 ka tawo",
    "mth-tag1": "Sports",
    "mth-tag2": "Mga Event",

    "facility-name-5": "RCC Assembly Hall",
    "facility-description-5": "Ang RCC Assembly Hall usa ka flexible nga lugar nga makadawat og hangtod sa 60 ka tawo sa classroom setting, 50 sa conference setting nga adunay mga lamesa, ug 40 para sa recollection activities. Adunay air conditioning, glass whiteboard, ug dakong screen, nga nagsiguro og komportable ug functional nga espasyo para sa lain-laing mga katigom.",
    "facility-capacity-value-5": "Hangtod sa 60 ka tawo",
    "ass-tag1": "Mga Espiritwal nga Aktibidad",
    "ass-tag2": "Mga Conference",

    "facility-name-6": "RCC Chapel",
    "facility-description-6": "Ang RCC Chapel nagtanyag og usa ka malinawon ug sagrado nga lugar para sa mga katigom, mga conference, mga espiritwal nga aktibidad, ug mga panahon sa pag-reflection. Gidesinyo aron mag-inspire sa pagtuo ug maghatag og kahulugan sa komunidad, kini nga lugar perpekto alang sa mga katigom nga nagtinguha sa pagpalig-on sa espiritu ug pagpalig-on sa mga relasyon.",
    "facility-capacity-value-6": "Hangtod sa 100 ka tawo",
    "chap-tag1": "Mga Espiritwal nga Aktibidad",
    "chap-tag2": "Mga Conference",

    "facility-name-7": "RCC Corporate Hall",
    "facility-description-7": "Ang RCC Corporate Hall usa ka versatile ug komportable nga lugar nga makadawat og hangtod sa 60 ka tawo sa classroom setup, 50 sa conference setup nga adunay mga lamesa, ug 40 para sa recollections. Kompleto sa air conditioning, glass whiteboard, ug dakong screen, kini usa ka perpekto nga lugar alang sa mga professional ug espiritwal nga mga katigom.",
    "facility-capacity-value-7": "Hangtod sa 60 ka tawo",
    "corp-tag1": "Classroom",
    "corp-tag2": "Mga Conference",

    "facility-name-8": "Swimming Pool",
    "facility-description-8": "Ang unibersidad nag-invest og usa ka Olympic-sized nga swimming pool nga magamit para sa mga klase sa Physical Education sa mga estudyante ug mga programang sertipikasyon sa swimming. Ang pool naghatag og resort-like nga impression, nga napalibutan sa kalikupan, adunay covered concrete bleachers sa wala ug 12 shower areas ug 52 cubicles sa pikas bahin.",
    "facility-capacity-value-8": "Hangtod sa 25 ka tawo",
    "swim-tag1": "Sports",
    "swim-tag2": "Olympic Size",
    "swim-tag3": "Physical Education",

    "facility-name-9": "Athletic Track",
    "facility-description-9": "Ang athletic track anaa duol sa Ugnayang La Salle ug magamit sa mga estudyante ug staff sa unibersidad alang sa physical fitness ug training. Ang football field usab magamit nga lugar para sa training sa mga atleta sa tibuok semana.",
    "facility-capacity-value-9": "Hangtod sa 500 ka tawo",
    "oval-tag1": "Sports",
    "oval-tag2": "Training",
    "oval-tag3": "Physical Education",


      "event-name-label": "Ngalan sa Kalihokan",
      "attendees-label": "Ihap sa mga Partisipante",
      "pick-date-time": "Pagpili sa Petsa ug Oras",
      "morning": "Buntag",
      "afternoon": "Hapon",
      "regular-hours": "Regular nga Oras",
      "late-hours": "Ulahing mga Oras",
      "evening": "Gabii",
      "wholeday": "Tibuok Adlaw",
      "schedule-btn": "I-schedule ang Kalihokan",
    },
    ilo: {
      "facility-name-1": "Ugnayang La Salle",
      "facility-description-1": "Ugnayang La Salle, ti kadakkel nga venue ti De La Salle University-Dasmariñas, ket napnek iti aircon ken adda dagiti ayan para iti concerts, conferences, ken ceremonies.",
      "facility-capacity-1": "Kapasidad:",
      "facility-capacity-value-1": "Upto iti 2000 nga tao",
      "tag-event-venue": "Venue ti Okasyon",
      "tag-large-capacity": "Dakkel nga Kapasidad",
      "event-details-title": "Dagiti Detalye ti Okasyon",

      "facility-name-2": "Football Field",
    "facility-description-2": "Ti football field ti DLSU-D ket agserbi kas ti pangunang lugar para ti panagsanay iti football, dagiti dakel a demostrasyon, ken sabali a kultural ken sibil a pangyayari. Ti nasayaat ken nalinis a daga ket mangited iti nalatak a lugar para ti panagsanay ti atletiko ken dagiti dakkel a pagtitipon.",
    "facility-capacity-value-2": "Agtalinaed iti 400 nga tao",
    "field-tag1": "Sports",
    "field-tag2": "Konsyertos",
    "field-tag3": "Aktibidad ti Estudyante",
    "field-tag4": "Kultural a Pangyayari",

    "facility-name-3": "Grandstand",
    "facility-description-3": "Ti grandstand ti DLSU-D ket mangted iti lugar para ti publiko nga mangkitkita ti live a sporting events. Usarento pay a kas lugar para kadagiti alternative a klase no ti magtutudlo ken estudyante ket agpili nga ag outdoor tapno makaliklik iti naurnos nga panagadal.",
    "facility-capacity-value-3": "Agtalinaed iti 400 nga tao",
    "grand-tag1": "Pangyayari",
    "grand-tag2": "Konsyertos",
    "grand-tag3": "Aktibidad ti Estudyante",

    "facility-name-4": "Mth Court",
    "facility-description-4": "Ti MTH Court ket maysa a lugar a nababalin para kadagiti sports ken pangyayari, nga mangted iti nasayaat ken dinamik a lugar nga perpekto para iti atletiko a aktibidad, torneo, ken espesyal a pagtitipon.",
    "facility-capacity-value-4": "Agtalinaed iti 500 nga tao",
    "mth-tag1": "Sports",
    "mth-tag2": "Pangyayari",

    "facility-name-5": "RCC Assembly Hall",
    "facility-description-5": "Ti RCC Assembly Hall ket maysa a flexible nga lugar a mangted iti kapasidad iti 60 nga tao iti classroom setup, 50 iti conference setup a nakalamesa, ken 40 para kadagiti recollection a aktibidad. Adda air conditioning, glass whiteboard, ken dakdakkel a screen, a mangted iti komportable ken functional nga espasyo para kadagiti nasapa a pagtitipon.",
    "facility-capacity-value-5": "Agtalinaed iti 60 nga tao",
    "ass-tag1": "Aktibidad Espiritwal",
    "ass-tag2": "Conference",

    "facility-name-6": "RCC Chapel",
    "facility-description-6": "Ti RCC Chapel ket mangted iti maysa a naimbag ken sagrado nga lugar para kadagiti pagtitipon, konferensiya, aktibidad espiritwal, ken oras a pang-reflection. Naidisenyo a mangted iti inspiration iti pammati ken mangpapigsa iti komunidad, kas maysa nga lugar para kadagiti pagtitipon a mangpatalinaed iti espiritu ken mangpabaknang kadagiti relasyon.",
    "facility-capacity-value-6": "Agtalinaed iti 100 nga tao",
    "chap-tag1": "Aktibidad Espiritwal",
    "chap-tag2": "Conference",

    "facility-name-7": "RCC Corporate Hall",
    "facility-description-7": "Ti RCC Corporate Hall ket flexible ken komportable nga lugar a mangted iti kapasidad iti 60 nga tao iti classroom setup, 50 iti conference setup a nakalamesa, ken 40 para kadagiti recollections. Adda air conditioning, glass whiteboard, ken dakdakkel a screen, a mangted iti nasayaat nga lugar para kadagiti propesyonal ken espiritwal a pagtitipon.",
    "facility-capacity-value-7": "Agtalinaed iti 60 nga tao",
    "corp-tag1": "Classroom",
    "corp-tag2": "Conference",

    "facility-name-8": "Swimming Pool",
    "facility-description-8": "Ti unibersidad ket nag-invest iti Olympic-sized nga swimming pool a magamit para iti klase ti Physical Education para kadagiti estudyante ken kadagiti certification program para iti swimming. Ti pool ket mangted iti resort-like nga impresyon, a napalibutan ti kalikasan, adda covered concrete bleachers iti wata ken 12 nga shower areas ken 52 nga cubicles iti kabilugan.",
    "facility-capacity-value-8": "Agtalinaed iti 25 nga tao",
    "swim-tag1": "Sports",
    "swim-tag2": "Olympic Size",
    "swim-tag3": "Physical Education",

    "facility-name-9": "Athletic Track",
    "facility-description-9": "Ti athletic track ket addaan iti Ugnayang La Salle ken magamit para iti panagsanay ken fitness a aktibidad kadagiti estudyante ken staff ti unibersidad. Ti football field met ket magamit nga lugar para iti panagsanay ti mga atleta iti amin a lawas ti semana.",
    "facility-capacity-value-9": "Agtalinaed iti 500 nga tao",
    "oval-tag1": "Sports",
    "oval-tag2": "Training",
    "oval-tag3": "Physical Education",

      "event-name-label": "Nagan ti Okasyon",
      "attendees-label": "Bilang ti Agturong",
      "pick-date-time": "Agnayon iti Petsa ken Oras",
      "morning": "Bigat",
      "afternoon": "Malem",
      "regular-hours": "Regular nga Oras",
    },
    waray: {
        "facility-name-1": "Ugnayang La Salle",
        "facility-description-1": "An Ugnayang La Salle amo an gidadako-i nga lugar para ha mga okasyon ha De La Salle University-Dasmariñas, nga kompleto hin aircon ngan haros igo para ha concerts, conferences, ngan mga seremonya.",
        "facility-capacity-1": "Kapasidad:",
        "facility-capacity-value-1": "Hasta 2000 nga tawo",
        "tag-event-venue": "Lugar han Okasyon",
        "tag-large-capacity": "Dako nga Kapasidad",
        "event-details-title": "Mga Detalye han Okasyon",

        "facility-name-2": "Football Field",
    "facility-description-2": "An football field han DLSU-D amo an panguna nga lugar para han mga praktis ha football, mga dako nga demonstrasyon, ngan iba pang mga kultural ngan sibiko nga kalihokan. An dako ngan maopay nga luna nagtutugot han hingpit nga lugar para ha athletic nga praktis ngan mga dagko nga pagtitipon.",
    "facility-capacity-value-2": "Hangtod 400 ka tawo",
    "field-tag1": "Sports",
    "field-tag2": "Konsyertos",
    "field-tag3": "Aktibidad han Estudyante",
    "field-tag4": "Kultural nga Pangyayari",

    "facility-name-3": "Grandstand",
    "facility-description-3": "An grandstand han DLSU-D nagtutugot han publiko nga makatan-aw han live nga sporting events. Gagamiton gihapon ini kas lugar para han alternative nga klase kon an mga magtutdo ngan estudyante magpipili nga mag-outdoor ha mga lain nga setting han pag-adal.",
    "facility-capacity-value-3": "Hangtod 400 ka tawo",
    "grand-tag1": "Pangyayari",
    "grand-tag2": "Konsyertos",
    "grand-tag3": "Aktibidad han Estudyante",

    "facility-name-4": "Mth Court",
    "facility-description-4": "An MTH Court usa ka lugar nga versatile para ha mga sports ngan mga pangyayari, nagtutugot han halapad ngan dinamik nga luna nga perpekto para ha athletic nga aktibidad, mga torneo, ngan espesyal nga mga pagtitipon.",
    "facility-capacity-value-4": "Hangtod 500 ka tawo",
    "mth-tag1": "Sports",
    "mth-tag2": "Pangyayari",

    "facility-name-5": "RCC Assembly Hall",
    "facility-description-5": "An RCC Assembly Hall usa ka flexible nga lugar nga nagtutugot han kapasidad nga 60 ka tawo ha classroom setup, 50 ha conference setup nga may mga lamesa, ngan 40 para ha recollection nga aktibidad. Adunay air conditioning, glass whiteboard, ngan dako nga screen, nga naghahatag hin komportable ngan functional nga lugar para han mga pagtitipon.",
    "facility-capacity-value-5": "Hangtod 60 ka tawo",
    "ass-tag1": "Mga Espiritwal nga Aktibidad",
    "ass-tag2": "Conference",

    "facility-name-6": "RCC Chapel",
    "facility-description-6": "An RCC Chapel nagtutugot hin usa ka malinawon ngan sagrado nga lugar para han mga pagtitipon, mga conference, mga espiritwal nga aktibidad, ngan mga oras han reflection. Gidesinyo ini para maghatag hin inspirasyon ha pagtuo ngan magpapasig-uli han komunidad, nga usa nga lugar para ha mga pagtitipon nga magpapaligo han espiritu ngan magpapalig-on han mga relasyon.",
    "facility-capacity-value-6": "Hangtod 100 ka tawo",
    "chap-tag1": "Mga Espiritwal nga Aktibidad",
    "chap-tag2": "Conference",

    "facility-name-7": "RCC Corporate Hall",
    "facility-description-7": "An RCC Corporate Hall usa ka flexible ngan komportable nga lugar nga nagtutugot han kapasidad nga 60 ka tawo ha classroom setup, 50 ha conference setup nga may mga lamesa, ngan 40 para ha recollections. Adunay air conditioning, glass whiteboard, ngan dako nga screen, nga naghahatag hin perpekto nga lugar para han mga professional ngan espiritwal nga pagtitipon.",
    "facility-capacity-value-7": "Hangtod 60 ka tawo",
    "corp-tag1": "Classroom",
    "corp-tag2": "Conference",

    "facility-name-8": "Swimming Pool",
    "facility-description-8": "An unibersidad nag-invest hin Olympic-sized nga swimming pool nga magagamit para han mga klase ha Physical Education han mga estudyante ngan mga sertipikasyon nga programa ha swimming. An pool naghatag hin resort-like nga impresyon, nga napalibutan han kalikupan, nga may covered concrete bleachers ha wala ngan 12 nga shower areas ngan 52 nga cubicles ha pikas bahin.",
    "facility-capacity-value-8": "Hangtod 25 ka tawo",
    "swim-tag1": "Sports",
    "swim-tag2": "Olympic Size",
    "swim-tag3": "Physical Education",

    "facility-name-9": "Athletic Track",
    "facility-description-9": "An athletic track anaa duol sa Ugnayang La Salle ngan magagamit para ha mga estudyante ngan staff han unibersidad para ha fitness nga aktibidad ug panagsanay. An football field magagamit gihapon nga lugar para ha training han mga atleta ha bug-os nga semana.",
    "facility-capacity-value-9": "Hangtod 500 ka tawo",
    "oval-tag1": "Sports",
    "oval-tag2": "Training",
    "oval-tag3": "Physical Education",

        "event-name-label": "Ngaran han Okasyon",
        "attendees-label": "Kadamo han mga Mag-aatendir",
        "pick-date-time": "Pili hin Petsa ngan Oras",
        "morning": "Buntag",
        "afternoon": "Kulop",
        "regular-hours": "Regular nga Oras",
        "late-hours": "Ihinai nga Oras",
        "evening": "Gab-i",
        "wholeday": "Bug-os nga Adlaw",
        "schedule-btn": "I-Schedule an Okasyon",
      },
      jp: {
        "facility-name-1": "Ugnayang La Salle",
        "facility-description-1": "Ugnayang La Salleは、De La Salle大学ダスマリニャス校で最大のイベント会場で、空調完備で、コンサート、会議、式典に十分な座席を備えています。",
        "facility-capacity-1": "収容人数：",
        "facility-capacity-value-1": "最大2000人",
        "tag-event-venue": "イベント会場",
        "tag-large-capacity": "大容量",
        "event-details-title": "イベント詳細",

        "facility-name-2": "サッカー場",
    "facility-description-2": "DLSU-Dのサッカー場は、サッカーの練習、大規模なイベント、およびその他の文化的・市民的活動のための主要な場所です。広大で優れた施設は、スポーツの練習や大規模な集会に最適な場所を提供します。",
    "facility-capacity-value-2": "最大400人",
    "field-tag1": "スポーツ",
    "field-tag2": "コンサート",
    "field-tag3": "学生活動",
    "field-tag4": "文化イベント",

    "facility-name-3": "グランドスタンド",
    "facility-description-3": "DLSU-Dのグランドスタンドは、ライブスポーツイベントを観戦するための公共の場所です。また、教師と学生が屋外で授業を受けるための代替の設定としても使用されます。",
    "facility-capacity-value-3": "最大400人",
    "grand-tag1": "イベント",
    "grand-tag2": "コンサート",
    "grand-tag3": "学生活動",

    "facility-name-4": "MTH Court",
    "facility-description-4": "MTH Courtは、スポーツイベントや会議に使用できる多目的な施設で、広くて動的なスペースを提供します。これは、運動活動、トーナメント、特別な集会に最適な場所です。",
    "facility-capacity-value-4": "最大500人",
    "mth-tag1": "スポーツ",
    "mth-tag2": "イベント",

    "facility-name-5": "RCCアセンブリーホール",
    "facility-description-5": "RCCアセンブリーホールは、クラスルーム設定で最大60人、会議設定で50人、リコレクション活動のために40人を収容できる柔軟な会議場です。エアコン、ガラス製のホワイトボード、大画面が提供され、快適で機能的な場所を提供します。",
    "facility-capacity-value-5": "最大60人",
    "ass-tag1": "精神的活動",
    "ass-tag2": "会議",

    "facility-name-6": "RCCチャペル",
    "facility-description-6": "RCCチャペルは、集会、会議、精神的な活動、リフレクションの時間に最適な静かで神聖な場所です。信仰を励まし、コミュニティの絆を深める場所として設計されています。",
    "facility-capacity-value-6": "最大100人",
    "chap-tag1": "精神的活動",
    "chap-tag2": "会議",

    "facility-name-7": "RCCコーポレートホール",
    "facility-description-7": "RCCコーポレートホールは、クラスルーム設定で最大60人、会議設定で50人、リコレクション活動のために40人を収容できる柔軟で快適な場所です。エアコン、ガラス製のホワイトボード、大画面が提供され、専門的な集会や精神的な集まりに最適な場所です。",
    "facility-capacity-value-7": "最大60人",
    "corp-tag1": "クラスルーム",
    "corp-tag2": "会議",

    "facility-name-8": "プール",
    "facility-description-8": "この大学は、学生向けの体育の授業や水泳認定プログラムに使用されるオリンピックサイズのプールに投資しました。プールは自然に囲まれ、リゾートのような印象を与え、左側には屋根付きのコンクリートベンチ、右側には12のシャワーエリアと52の更衣室があります。",
    "facility-capacity-value-8": "最大25人",
    "swim-tag1": "スポーツ",
    "swim-tag2": "オリンピックサイズ",
    "swim-tag3": "体育",

    "facility-name-9": "陸上トラック",
    "facility-description-9": "陸上トラックはUgnayang La Salleの近くにあり、学生とスタッフのフィットネス活動や練習に使用されます。サッカー場も、週を通じてアスリートのトレーニングの場として利用されています。",
    "facility-capacity-value-9": "最大500人",
    "oval-tag1": "スポーツ",
    "oval-tag2": "トレーニング",
    "oval-tag3": "体育",


        "event-name-label": "イベント名",
        "attendees-label": "参加人数",
        "pick-date-time": "日付と時間を選択",
        "morning": "午前",
        "afternoon": "午後",
        "regular-hours": "通常の営業時間",
        "late-hours": "遅い時間",
        "evening": "夕方",
        "wholeday": "終日",
        "schedule-btn": "イベントをスケジュールする",
      },
      kr: {
        "facility-name-1": "Ugnayang La Salle",
        "facility-description-1": "Ugnayang La Salle는 De La Salle 대학 Dasmariñas 캠퍼스에서 가장 큰 이벤트 장소로, 에어컨이 완비되어 있으며 콘서트, 회의 및 행사에 충분한 좌석을 제공합니다.",
        "facility-capacity-1": "수용 인원:",
        "facility-capacity-value-1": "최대 2000명",
        "tag-event-venue": "이벤트 장소",
        "tag-large-capacity": "대용량",
        "event-details-title": "이벤트 세부 정보",

        "facility-name-2": "축구장",
        "facility-description-2": "DLSU-D의 축구장은 축구 훈련, 대규모 행사 및 기타 문화적, 시민적 활동을 위한 주요 장소입니다. 넓고 뛰어난 시설은 운동 훈련과 대규모 모임을 위한 최적의 공간을 제공합니다.",
        "facility-capacity-value-2": "최대 400명",
        "field-tag1": "스포츠",
        "field-tag2": "콘서트",
        "field-tag3": "학생 활동",
        "field-tag4": "문화 행사",
    
        "facility-name-3": "관람석",
        "facility-description-3": "DLSU-D의 관람석은 스포츠 이벤트를 실시간으로 관람할 수 있는 공공 장소입니다. 또한, 교수와 학생들이 야외에서 수업을 받을 수 있는 대체 학습 환경으로 사용됩니다.",
        "facility-capacity-value-3": "최대 400명",
        "grand-tag1": "행사",
        "grand-tag2": "콘서트",
        "grand-tag3": "학생 활동",
    
        "facility-name-4": "MTH 법원",
        "facility-description-4": "MTH 법원은 스포츠 행사와 회의에 사용될 수 있는 다목적 공간으로, 넓고 동적인 공간을 제공합니다. 운동 활동, 토너먼트 및 특별한 모임에 최적인 장소입니다.",
        "facility-capacity-value-4": "최대 500명",
        "mth-tag1": "스포츠",
        "mth-tag2": "행사",
    
        "facility-name-5": "RCC 회의실",
        "facility-description-5": "RCC 회의실은 교실 설정에서 최대 60명, 회의 설정에서 50명, 리콜 활동을 위해 40명을 수용할 수 있는 유연한 회의 장소입니다. 에어컨, 유리 화이트보드, 대형 화면이 제공되어 편안하고 기능적인 공간을 제공합니다.",
        "facility-capacity-value-5": "최대 60명",
        "ass-tag1": "영적 활동",
        "ass-tag2": "회의",
    
        "facility-name-6": "RCC 예배당",
        "facility-description-6": "RCC 예배당은 모임, 회의, 영적 활동 및 반성의 시간을 위한 조용하고 신성한 공간입니다. 믿음을 고취시키고 공동체의 유대를 강화하기 위한 장소로 설계되었습니다.",
        "facility-capacity-value-6": "최대 100명",
        "chap-tag1": "영적 활동",
        "chap-tag2": "회의",
    
        "facility-name-7": "RCC 기업 회의실",
        "facility-description-7": "RCC 기업 회의실은 교실 설정에서 최대 60명, 회의 설정에서 50명, 리콜 활동을 위해 40명을 수용할 수 있는 유연하고 편안한 공간입니다. 에어컨, 유리 화이트보드, 대형 화면이 제공되어 전문적이고 영적인 모임에 최적의 공간을 제공합니다.",
        "facility-capacity-value-7": "최대 60명",
        "corp-tag1": "교실",
        "corp-tag2": "회의",
    
        "facility-name-8": "수영장",
        "facility-description-8": "대학은 학생들을 위한 체육 수업 및 수영 인증 프로그램을 위해 올림픽 크기의 수영장에 투자했습니다. 이 수영장은 자연에 둘러싸여 있으며, 리조트 같은 인상을 주며, 왼쪽에는 지붕이 있는 콘크리트 관람석, 오른쪽에는 12개의 샤워 공간과 52개의 탈의실이 있습니다.",
        "facility-capacity-value-8": "최대 25명",
        "swim-tag1": "스포츠",
        "swim-tag2": "올림픽 크기",
        "swim-tag3": "체육",
    
        "facility-name-9": "육상 트랙",
        "facility-description-9": "육상 트랙은 Ugnayang La Salle 근처에 위치하며, 학생들과 교직원들이 피트니스 활동이나 훈련을 위해 사용합니다. 축구장도 일주일 내내 운동선수들의 훈련장소로 사용됩니다.",
        "facility-capacity-value-9": "최대 500명",
        "oval-tag1": "스포츠",
        "oval-tag2": "훈련",
        "oval-tag3": "체육",

        "event-name-label": "이벤트 이름",
        "attendees-label": "참가자 수",
        "pick-date-time": "날짜 및 시간 선택",
        "morning": "오전",
        "afternoon": "오후",
        "regular-hours": "정규 시간",
        "late-hours": "늦은 시간",
        "evening": "저녁",
        "wholeday": "종일",
        "schedule-btn": "이벤트 일정",
      },
      cn: {
        "facility-name-1": "Ugnayang La Salle",
        "facility-description-1": "Ugnayang La Salle 是德拉萨大学达斯马里尼亚斯校区最大的活动场地，配有全面空调，并提供充足的座位，可用于音乐会、会议和典礼。",
        "facility-capacity-1": "容纳人数：",
        "facility-capacity-value-1": "最多可容纳2000人",
        "tag-event-venue": "活动场地",
        "tag-large-capacity": "大容量",
        "event-details-title": "活动详情",

        "facility-name-2": "足球场",
    "facility-description-2": "DLSU-D的足球场是主要的场所，用于足球训练、大型活动和其他文化及市民活动。广阔且卓越的设施为体育训练和大型聚会提供了理想的场地。",
    "facility-capacity-value-2": "最多400人",
    "field-tag1": "体育",
    "field-tag2": "音乐会",
    "field-tag3": "学生活动",
    "field-tag4": "文化活动",

    "facility-name-3": "看台",
    "facility-description-3": "DLSU-D的看台是一个公共场所，用于观看现场体育赛事。此外，它也可以作为教师和学生在户外上课的替代场地。",
    "facility-capacity-value-3": "最多400人",
    "grand-tag1": "活动",
    "grand-tag2": "音乐会",
    "grand-tag3": "学生活动",

    "facility-name-4": "MTH 球场",
    "facility-description-4": "MTH 球场是一个多功能场地，可用于体育赛事和会议，提供宽敞且动态的空间。是运动活动、锦标赛和特别聚会的理想场所。",
    "facility-capacity-value-4": "最多500人",
    "mth-tag1": "体育",
    "mth-tag2": "活动",

    "facility-name-5": "RCC 会议室",
    "facility-description-5": "RCC 会议室是一个灵活的会议场所，可以容纳最多60人（课堂设置）、50人（会议设置）和40人（反思活动）。提供空调、玻璃白板和大屏幕，提供舒适和功能性空间。",
    "facility-capacity-value-5": "最多60人",
    "ass-tag1": "精神活动",
    "ass-tag2": "会议",

    "facility-name-6": "RCC 教堂",
    "facility-description-6": "RCC 教堂是一个宁静而神圣的地方，适合举办聚会、会议、精神活动和反思时光。旨在鼓励信仰并加强社区之间的联系。",
    "facility-capacity-value-6": "最多100人",
    "chap-tag1": "精神活动",
    "chap-tag2": "会议",

    "facility-name-7": "RCC 企业会议厅",
    "facility-description-7": "RCC 企业会议厅是一个灵活且舒适的场地，可容纳最多60人（课堂设置）、50人（会议设置）和40人（反思活动）。提供空调、玻璃白板和大屏幕，非常适合专业的会议和精神聚会。",
    "facility-capacity-value-7": "最多60人",
    "corp-tag1": "课堂",
    "corp-tag2": "会议",

    "facility-name-8": "游泳池",
    "facility-description-8": "该大学为学生体育课程和游泳认证项目投资了一个奥林匹克大小的游泳池。游泳池被自然环境所包围，给人一种度假村的感觉，左侧有带顶棚的混凝土长椅，右侧有12个淋浴区和52个更衣室。",
    "facility-capacity-value-8": "最多25人",
    "swim-tag1": "体育",
    "swim-tag2": "奥林匹克大小",
    "swim-tag3": "体育课程",

    "facility-name-9": "田径跑道",
    "facility-description-9": "田径跑道位于Ugnayang La Salle附近，供学生和员工进行健身活动和训练。足球场也在一周内为运动员提供训练。",
    "facility-capacity-value-9": "最多500人",
    "oval-tag1": "体育",
    "oval-tag2": "训练",
    "oval-tag3": "体育课程",

        "event-name-label": "活动名称",
        "attendees-label": "参加人数",
        "pick-date-time": "选择日期和时间",
        "morning": "早上",
        "afternoon": "下午",
        "regular-hours": "正常时间",
        "late-hours": "晚间时间",
        "evening": "晚上",
        "wholeday": "全天",
        "schedule-btn": "安排活动",
      },
    };
  
  function changeLanguage() {
    const lang = document.getElementById("language-select").value;
    const elements = document.querySelectorAll("[data-lang]");
  
    elements.forEach(element => {
      const key = element.getAttribute("data-lang");
      if (translations[lang] && translations[lang][key]) {
        element.textContent = translations[lang][key];
      }
    });
  }
  